webapp_project/movieproject/movieapp/urls.py
from django.urls import path
from . import views

# Namespace
app_name='movieapp'

urlpatterns = [
    path('',views.index,name='index'),
    path('movie/<int:movie_id>',views.detail,name='detail'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete'),
    ]

webapp_project/movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('movieapp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp_project/movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
    name = models.CharField(max_length=250)
    desc = models.TextField()
    year = models.IntegerField()
    img = models.ImageField(upload_to='gallery')

    def __str__(self):
        return self.name

webapp_project/movieproject/movieapp/forms.py
from django import forms
from .models import Movie

class MovieForm(forms.ModelForm):
    class Meta:
        model = Movie
        fields = ['name','desc','year','img']

webapp_project/movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

from movieapp.forms import MovieForm
from movieapp.models import Movie


# Create your views here.
def index(request):
    movie = Movie.objects.all()

    return render(request,'index.html', {'context': movie})

def detail(request,movie_id):
    movie = Movie.objects.get(id=movie_id)
    # return HttpResponse('This is movie no %s' % movie_id)
    return render(request,'detail.html',{'movie': movie})

def add_movie(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        desc = request.POST.get('description')
        year = request.POST.get('year')
        image = request.FILES['image']
        movie = Movie(name=name,desc=desc,year=year,img=image)
        movie.save()

    return render(request,'add.html')

def update(request,id):
    movie = Movie.objects.get(id=id)
    form = MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect('/')

    return render(request,'edit.html',{'form': form, 'movie': movie})
    # form = MovieForm(request.POST, request.FILES, instance=Movie.objects.get(id=id))
    # return render(request, 'edit.html',{'form': form})

def delete(request,id):
    if request.method == 'POST':
        movie = Movie.objects.get(id=id)
        movie.delete()
        return redirect('/')
    return render(request,'delete.html')

webapp_project/movieproject/templates/add.html
<form method="POST" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="Enter the movie name"> <br>
  <input type="text" name="description" placeholder="Enter the movie description"> <br>
  <input type="text" name="year" placeholder="Enter the movie year"> <br>
  <input type="file" name="image" > <br>
  <input type="submit" name="submit" > <br>
</form>

webapp_project/movieproject/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Movie</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<nav class="navbar bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      Online Movie store
    </a>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

webapp_project/movieproject/templates/delete.html
<form method="post">
  {% csrf_token %}
  Do you want to delete this movie?
  <input type="submit" >
<!--  <input type="submit" value="No">-->

</form>

webapp_project/movieproject/templates/detail.html
{% extends 'base.html' %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <img src="{{ movie.img.url }}" width="300" height="300">
        </div>
        <div class="col-md-6">
             <h2>{{ movie.name }} </h2>
            <h4>{{ movie.desc }}</h4>
            <h6>{{ movie.year }}</h6> <br>
            <a class="btn btn-warning"  href="{% url 'movieapp:update' movie.id %}">update</a>
            <a class="btn btn-danger"  href="{% url 'movieapp:delete' movie.id %}">Delete</a>
        </div>
    </div>
</div>
{% endblock %}

webapp_project/movieproject/templates/edit.html
<h1>Edit the movie here</h1>
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" name="submit">
</form>

webapp_project/movieproject/templates/index.html
{% extends 'base.html' %}

{% block body %}
<!--<div class="container">-->
<!--    <div class="column">-->
<!--        <div class="col-md-8">-->
            <h1>Movie List</h1>
            <a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}">Add movie</a>
<!--        </div>-->
<!--    </div>-->
<!--</div>-->

<!--<a class="btn btn-warning" href="{% url 'movieapp:add_movie' %}">Add movie</a>-->
<div class="container">
    <div class="row">
        {% for i in context %}
        <div class="col-md-3">
            <div class="card" style=" height: 40rem;">
                <img class="card-img-top" src="{{ i.img.url }}"  width="250px" height="250px" alt="Card image cap">
                    <div class="card-body">
                        <h5 class="card-title">{{ i.name }}</h5>
                        <p class="card-text">{{ i.desc }}</p>
                        <a href="{% url 'movieapp:detail' i.id %}" class="btn btn-primary">view details</a>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>


<!--{% for i in context %}-->
<!--<img src="{{ i.img.url }}" width="100" height="100">-->
<!--&lt;!&ndash;<a href="movie/{{ i.id }}" >{{ i.name }}</a> <br>&ndash;&gt;-->
<!--<a href="{% url 'movieapp:detail' i.id %}" >{{ i.name }}</a> <br>-->
<!--{% endfor %}-->

{% endblock %}